`timescale 1ns / 1ps

//==========================================================================
// Module: char_font
// Description: 8x8 glyph ROM, ASCII 0x20 to 0x5F. GENERATED by
//              bench/gen_tables.py - edit that, not this.
//
//   hex_font covers the sixteen hex digits and is what the camera
//   bring-up overlay uses. The centroid bench needs labels as well as
//   numbers - a screen reading STARS 11 is worth more than one reading
//   11 - so this carries the printable upper-case set.
//
//   Bit 7 of `bits` is the leftmost pixel. Glyphs are 5x7 inside the 8x8
//   cell, so text drawn edge to edge still has space between characters.
//   Characters with no glyph render blank, which is a visible mistake
//   rather than a silent one.
//==========================================================================

module char_font (
    input  wire [7:0] ch,       // ASCII; anything outside 0x20-0x5F is blank
    input  wire [2:0] row,      // 0 = top row of the glyph
    output wire [7:0] bits
);

    (* rom_style = "distributed" *) reg [7:0] tbl [0:511];

    initial begin
        // 'space'
        tbl[  0] = 8'h00; tbl[  1] = 8'h00; tbl[  2] = 8'h00; tbl[  3] = 8'h00; tbl[  4] = 8'h00; tbl[  5] = 8'h00; tbl[  6] = 8'h00; tbl[  7] = 8'h00;
        // '!'
        tbl[  8] = 8'h00; tbl[  9] = 8'h00; tbl[ 10] = 8'h00; tbl[ 11] = 8'h00; tbl[ 12] = 8'h00; tbl[ 13] = 8'h00; tbl[ 14] = 8'h00; tbl[ 15] = 8'h00;
        // '"'
        tbl[ 16] = 8'h00; tbl[ 17] = 8'h00; tbl[ 18] = 8'h00; tbl[ 19] = 8'h00; tbl[ 20] = 8'h00; tbl[ 21] = 8'h00; tbl[ 22] = 8'h00; tbl[ 23] = 8'h00;
        // '#'
        tbl[ 24] = 8'h00; tbl[ 25] = 8'h00; tbl[ 26] = 8'h00; tbl[ 27] = 8'h00; tbl[ 28] = 8'h00; tbl[ 29] = 8'h00; tbl[ 30] = 8'h00; tbl[ 31] = 8'h00;
        // '$'
        tbl[ 32] = 8'h00; tbl[ 33] = 8'h00; tbl[ 34] = 8'h00; tbl[ 35] = 8'h00; tbl[ 36] = 8'h00; tbl[ 37] = 8'h00; tbl[ 38] = 8'h00; tbl[ 39] = 8'h00;
        // '%'
        tbl[ 40] = 8'h64; tbl[ 41] = 8'h68; tbl[ 42] = 8'h08; tbl[ 43] = 8'h10; tbl[ 44] = 8'h20; tbl[ 45] = 8'h2C; tbl[ 46] = 8'h4C; tbl[ 47] = 8'h00;
        // '&'
        tbl[ 48] = 8'h00; tbl[ 49] = 8'h00; tbl[ 50] = 8'h00; tbl[ 51] = 8'h00; tbl[ 52] = 8'h00; tbl[ 53] = 8'h00; tbl[ 54] = 8'h00; tbl[ 55] = 8'h00;
        // '''
        tbl[ 56] = 8'h00; tbl[ 57] = 8'h00; tbl[ 58] = 8'h00; tbl[ 59] = 8'h00; tbl[ 60] = 8'h00; tbl[ 61] = 8'h00; tbl[ 62] = 8'h00; tbl[ 63] = 8'h00;
        // '('
        tbl[ 64] = 8'h00; tbl[ 65] = 8'h00; tbl[ 66] = 8'h00; tbl[ 67] = 8'h00; tbl[ 68] = 8'h00; tbl[ 69] = 8'h00; tbl[ 70] = 8'h00; tbl[ 71] = 8'h00;
        // ')'
        tbl[ 72] = 8'h00; tbl[ 73] = 8'h00; tbl[ 74] = 8'h00; tbl[ 75] = 8'h00; tbl[ 76] = 8'h00; tbl[ 77] = 8'h00; tbl[ 78] = 8'h00; tbl[ 79] = 8'h00;
        // '*'
        tbl[ 80] = 8'h00; tbl[ 81] = 8'h54; tbl[ 82] = 8'h38; tbl[ 83] = 8'h7C; tbl[ 84] = 8'h38; tbl[ 85] = 8'h54; tbl[ 86] = 8'h00; tbl[ 87] = 8'h00;
        // '+'
        tbl[ 88] = 8'h00; tbl[ 89] = 8'h10; tbl[ 90] = 8'h10; tbl[ 91] = 8'h7C; tbl[ 92] = 8'h10; tbl[ 93] = 8'h10; tbl[ 94] = 8'h00; tbl[ 95] = 8'h00;
        // ','
        tbl[ 96] = 8'h00; tbl[ 97] = 8'h00; tbl[ 98] = 8'h00; tbl[ 99] = 8'h00; tbl[100] = 8'h00; tbl[101] = 8'h00; tbl[102] = 8'h00; tbl[103] = 8'h00;
        // '-'
        tbl[104] = 8'h00; tbl[105] = 8'h00; tbl[106] = 8'h00; tbl[107] = 8'h7C; tbl[108] = 8'h00; tbl[109] = 8'h00; tbl[110] = 8'h00; tbl[111] = 8'h00;
        // '.'
        tbl[112] = 8'h00; tbl[113] = 8'h00; tbl[114] = 8'h00; tbl[115] = 8'h00; tbl[116] = 8'h00; tbl[117] = 8'h30; tbl[118] = 8'h30; tbl[119] = 8'h00;
        // '/'
        tbl[120] = 8'h04; tbl[121] = 8'h08; tbl[122] = 8'h08; tbl[123] = 8'h10; tbl[124] = 8'h20; tbl[125] = 8'h20; tbl[126] = 8'h40; tbl[127] = 8'h00;
        // '0'
        tbl[128] = 8'h38; tbl[129] = 8'h44; tbl[130] = 8'h4C; tbl[131] = 8'h54; tbl[132] = 8'h64; tbl[133] = 8'h44; tbl[134] = 8'h38; tbl[135] = 8'h00;
        // '1'
        tbl[136] = 8'h10; tbl[137] = 8'h30; tbl[138] = 8'h10; tbl[139] = 8'h10; tbl[140] = 8'h10; tbl[141] = 8'h10; tbl[142] = 8'h38; tbl[143] = 8'h00;
        // '2'
        tbl[144] = 8'h38; tbl[145] = 8'h44; tbl[146] = 8'h04; tbl[147] = 8'h08; tbl[148] = 8'h10; tbl[149] = 8'h20; tbl[150] = 8'h7C; tbl[151] = 8'h00;
        // '3'
        tbl[152] = 8'h7C; tbl[153] = 8'h08; tbl[154] = 8'h10; tbl[155] = 8'h08; tbl[156] = 8'h04; tbl[157] = 8'h44; tbl[158] = 8'h38; tbl[159] = 8'h00;
        // '4'
        tbl[160] = 8'h08; tbl[161] = 8'h18; tbl[162] = 8'h28; tbl[163] = 8'h48; tbl[164] = 8'h7C; tbl[165] = 8'h08; tbl[166] = 8'h08; tbl[167] = 8'h00;
        // '5'
        tbl[168] = 8'h7C; tbl[169] = 8'h40; tbl[170] = 8'h78; tbl[171] = 8'h04; tbl[172] = 8'h04; tbl[173] = 8'h44; tbl[174] = 8'h38; tbl[175] = 8'h00;
        // '6'
        tbl[176] = 8'h18; tbl[177] = 8'h20; tbl[178] = 8'h40; tbl[179] = 8'h78; tbl[180] = 8'h44; tbl[181] = 8'h44; tbl[182] = 8'h38; tbl[183] = 8'h00;
        // '7'
        tbl[184] = 8'h7C; tbl[185] = 8'h04; tbl[186] = 8'h08; tbl[187] = 8'h10; tbl[188] = 8'h20; tbl[189] = 8'h20; tbl[190] = 8'h20; tbl[191] = 8'h00;
        // '8'
        tbl[192] = 8'h38; tbl[193] = 8'h44; tbl[194] = 8'h44; tbl[195] = 8'h38; tbl[196] = 8'h44; tbl[197] = 8'h44; tbl[198] = 8'h38; tbl[199] = 8'h00;
        // '9'
        tbl[200] = 8'h38; tbl[201] = 8'h44; tbl[202] = 8'h44; tbl[203] = 8'h3C; tbl[204] = 8'h04; tbl[205] = 8'h08; tbl[206] = 8'h30; tbl[207] = 8'h00;
        // ':'
        tbl[208] = 8'h00; tbl[209] = 8'h30; tbl[210] = 8'h30; tbl[211] = 8'h00; tbl[212] = 8'h30; tbl[213] = 8'h30; tbl[214] = 8'h00; tbl[215] = 8'h00;
        // ';'
        tbl[216] = 8'h00; tbl[217] = 8'h00; tbl[218] = 8'h00; tbl[219] = 8'h00; tbl[220] = 8'h00; tbl[221] = 8'h00; tbl[222] = 8'h00; tbl[223] = 8'h00;
        // '<'
        tbl[224] = 8'h08; tbl[225] = 8'h10; tbl[226] = 8'h20; tbl[227] = 8'h40; tbl[228] = 8'h20; tbl[229] = 8'h10; tbl[230] = 8'h08; tbl[231] = 8'h00;
        // '='
        tbl[232] = 8'h00; tbl[233] = 8'h7C; tbl[234] = 8'h00; tbl[235] = 8'h00; tbl[236] = 8'h7C; tbl[237] = 8'h00; tbl[238] = 8'h00; tbl[239] = 8'h00;
        // '>'
        tbl[240] = 8'h20; tbl[241] = 8'h10; tbl[242] = 8'h08; tbl[243] = 8'h04; tbl[244] = 8'h08; tbl[245] = 8'h10; tbl[246] = 8'h20; tbl[247] = 8'h00;
        // '?'
        tbl[248] = 8'h00; tbl[249] = 8'h00; tbl[250] = 8'h00; tbl[251] = 8'h00; tbl[252] = 8'h00; tbl[253] = 8'h00; tbl[254] = 8'h00; tbl[255] = 8'h00;
        // '@'
        tbl[256] = 8'h00; tbl[257] = 8'h00; tbl[258] = 8'h00; tbl[259] = 8'h00; tbl[260] = 8'h00; tbl[261] = 8'h00; tbl[262] = 8'h00; tbl[263] = 8'h00;
        // 'A'
        tbl[264] = 8'h38; tbl[265] = 8'h44; tbl[266] = 8'h44; tbl[267] = 8'h7C; tbl[268] = 8'h44; tbl[269] = 8'h44; tbl[270] = 8'h44; tbl[271] = 8'h00;
        // 'B'
        tbl[272] = 8'h78; tbl[273] = 8'h44; tbl[274] = 8'h44; tbl[275] = 8'h78; tbl[276] = 8'h44; tbl[277] = 8'h44; tbl[278] = 8'h78; tbl[279] = 8'h00;
        // 'C'
        tbl[280] = 8'h38; tbl[281] = 8'h44; tbl[282] = 8'h40; tbl[283] = 8'h40; tbl[284] = 8'h40; tbl[285] = 8'h44; tbl[286] = 8'h38; tbl[287] = 8'h00;
        // 'D'
        tbl[288] = 8'h70; tbl[289] = 8'h48; tbl[290] = 8'h44; tbl[291] = 8'h44; tbl[292] = 8'h44; tbl[293] = 8'h48; tbl[294] = 8'h70; tbl[295] = 8'h00;
        // 'E'
        tbl[296] = 8'h7C; tbl[297] = 8'h40; tbl[298] = 8'h40; tbl[299] = 8'h78; tbl[300] = 8'h40; tbl[301] = 8'h40; tbl[302] = 8'h7C; tbl[303] = 8'h00;
        // 'F'
        tbl[304] = 8'h7C; tbl[305] = 8'h40; tbl[306] = 8'h40; tbl[307] = 8'h78; tbl[308] = 8'h40; tbl[309] = 8'h40; tbl[310] = 8'h40; tbl[311] = 8'h00;
        // 'G'
        tbl[312] = 8'h38; tbl[313] = 8'h44; tbl[314] = 8'h40; tbl[315] = 8'h5C; tbl[316] = 8'h44; tbl[317] = 8'h44; tbl[318] = 8'h3C; tbl[319] = 8'h00;
        // 'H'
        tbl[320] = 8'h44; tbl[321] = 8'h44; tbl[322] = 8'h44; tbl[323] = 8'h7C; tbl[324] = 8'h44; tbl[325] = 8'h44; tbl[326] = 8'h44; tbl[327] = 8'h00;
        // 'I'
        tbl[328] = 8'h38; tbl[329] = 8'h10; tbl[330] = 8'h10; tbl[331] = 8'h10; tbl[332] = 8'h10; tbl[333] = 8'h10; tbl[334] = 8'h38; tbl[335] = 8'h00;
        // 'J'
        tbl[336] = 8'h1C; tbl[337] = 8'h08; tbl[338] = 8'h08; tbl[339] = 8'h08; tbl[340] = 8'h08; tbl[341] = 8'h48; tbl[342] = 8'h30; tbl[343] = 8'h00;
        // 'K'
        tbl[344] = 8'h44; tbl[345] = 8'h48; tbl[346] = 8'h50; tbl[347] = 8'h60; tbl[348] = 8'h50; tbl[349] = 8'h48; tbl[350] = 8'h44; tbl[351] = 8'h00;
        // 'L'
        tbl[352] = 8'h40; tbl[353] = 8'h40; tbl[354] = 8'h40; tbl[355] = 8'h40; tbl[356] = 8'h40; tbl[357] = 8'h40; tbl[358] = 8'h7C; tbl[359] = 8'h00;
        // 'M'
        tbl[360] = 8'h44; tbl[361] = 8'h6C; tbl[362] = 8'h54; tbl[363] = 8'h54; tbl[364] = 8'h44; tbl[365] = 8'h44; tbl[366] = 8'h44; tbl[367] = 8'h00;
        // 'N'
        tbl[368] = 8'h44; tbl[369] = 8'h64; tbl[370] = 8'h54; tbl[371] = 8'h4C; tbl[372] = 8'h44; tbl[373] = 8'h44; tbl[374] = 8'h44; tbl[375] = 8'h00;
        // 'O'
        tbl[376] = 8'h38; tbl[377] = 8'h44; tbl[378] = 8'h44; tbl[379] = 8'h44; tbl[380] = 8'h44; tbl[381] = 8'h44; tbl[382] = 8'h38; tbl[383] = 8'h00;
        // 'P'
        tbl[384] = 8'h78; tbl[385] = 8'h44; tbl[386] = 8'h44; tbl[387] = 8'h78; tbl[388] = 8'h40; tbl[389] = 8'h40; tbl[390] = 8'h40; tbl[391] = 8'h00;
        // 'Q'
        tbl[392] = 8'h38; tbl[393] = 8'h44; tbl[394] = 8'h44; tbl[395] = 8'h44; tbl[396] = 8'h54; tbl[397] = 8'h48; tbl[398] = 8'h34; tbl[399] = 8'h00;
        // 'R'
        tbl[400] = 8'h78; tbl[401] = 8'h44; tbl[402] = 8'h44; tbl[403] = 8'h78; tbl[404] = 8'h50; tbl[405] = 8'h48; tbl[406] = 8'h44; tbl[407] = 8'h00;
        // 'S'
        tbl[408] = 8'h3C; tbl[409] = 8'h40; tbl[410] = 8'h40; tbl[411] = 8'h38; tbl[412] = 8'h04; tbl[413] = 8'h04; tbl[414] = 8'h78; tbl[415] = 8'h00;
        // 'T'
        tbl[416] = 8'h7C; tbl[417] = 8'h10; tbl[418] = 8'h10; tbl[419] = 8'h10; tbl[420] = 8'h10; tbl[421] = 8'h10; tbl[422] = 8'h10; tbl[423] = 8'h00;
        // 'U'
        tbl[424] = 8'h44; tbl[425] = 8'h44; tbl[426] = 8'h44; tbl[427] = 8'h44; tbl[428] = 8'h44; tbl[429] = 8'h44; tbl[430] = 8'h38; tbl[431] = 8'h00;
        // 'V'
        tbl[432] = 8'h44; tbl[433] = 8'h44; tbl[434] = 8'h44; tbl[435] = 8'h44; tbl[436] = 8'h44; tbl[437] = 8'h28; tbl[438] = 8'h10; tbl[439] = 8'h00;
        // 'W'
        tbl[440] = 8'h44; tbl[441] = 8'h44; tbl[442] = 8'h44; tbl[443] = 8'h54; tbl[444] = 8'h54; tbl[445] = 8'h6C; tbl[446] = 8'h44; tbl[447] = 8'h00;
        // 'X'
        tbl[448] = 8'h44; tbl[449] = 8'h44; tbl[450] = 8'h28; tbl[451] = 8'h10; tbl[452] = 8'h28; tbl[453] = 8'h44; tbl[454] = 8'h44; tbl[455] = 8'h00;
        // 'Y'
        tbl[456] = 8'h44; tbl[457] = 8'h44; tbl[458] = 8'h28; tbl[459] = 8'h10; tbl[460] = 8'h10; tbl[461] = 8'h10; tbl[462] = 8'h10; tbl[463] = 8'h00;
        // 'Z'
        tbl[464] = 8'h7C; tbl[465] = 8'h04; tbl[466] = 8'h08; tbl[467] = 8'h10; tbl[468] = 8'h20; tbl[469] = 8'h40; tbl[470] = 8'h7C; tbl[471] = 8'h00;
        // '['
        tbl[472] = 8'h38; tbl[473] = 8'h20; tbl[474] = 8'h20; tbl[475] = 8'h20; tbl[476] = 8'h20; tbl[477] = 8'h20; tbl[478] = 8'h38; tbl[479] = 8'h00;
        // '\'
        tbl[480] = 8'h00; tbl[481] = 8'h00; tbl[482] = 8'h00; tbl[483] = 8'h00; tbl[484] = 8'h00; tbl[485] = 8'h00; tbl[486] = 8'h00; tbl[487] = 8'h00;
        // ']'
        tbl[488] = 8'h38; tbl[489] = 8'h08; tbl[490] = 8'h08; tbl[491] = 8'h08; tbl[492] = 8'h08; tbl[493] = 8'h08; tbl[494] = 8'h38; tbl[495] = 8'h00;
        // '^'
        tbl[496] = 8'h00; tbl[497] = 8'h00; tbl[498] = 8'h00; tbl[499] = 8'h00; tbl[500] = 8'h00; tbl[501] = 8'h00; tbl[502] = 8'h00; tbl[503] = 8'h00;
        // '_'
        tbl[504] = 8'h00; tbl[505] = 8'h00; tbl[506] = 8'h00; tbl[507] = 8'h00; tbl[508] = 8'h00; tbl[509] = 8'h00; tbl[510] = 8'h00; tbl[511] = 8'h00;
    end

    wire in_range = (ch >= 8'h20) && (ch <= 8'h5F);

    // The table starts at 0x20, so the glyph index is ch - 0x20, not
    // ch[5:0]. Those differ by 32 with a wrap, which does not look like a
    // fault - every character still renders, just a different one - so it
    // survives right up until someone reads the screen: STARFRONT came out
    // as 34 2 2/.4, which is exactly S->3, T->4, A->blank, R->2.
    wire [5:0] gidx = ch[5:0] - 6'd32;

    assign bits = in_range ? tbl[{gidx, row}] : 8'h00;

endmodule
